import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({
	subsets: ['latin'],
	weight: '300',
});

export const metadata: Metadata = {
	title: 'Portfolio',
	description: 'Website generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html className={inter.className} lang='en'>
			<body suppressHydrationWarning>{children}</body>
		</html>
	);
}
